blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.blog_list, name='blog_list'),
    url(r'^new/$', views.crawler_new, name='crawler_new'),
    url(r'^(?P<pk>\d+)/edit/$', views.blog_edit, name='blog_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.blog_delete, name='blog_delete'),
    url(r'^(?P<pk>\d+)/$', views.blog_detail, name='blog_detail'),
    url(r'^profile/$', views.profile, name='profile'),
]

transmedia/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.shortcuts import redirect
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from crawler.models import *

# Create your models here.

class Post(models.Model):
    target_url = models.URLField()
    eng_title = models.TextField()
    kor_title = models.TextField()
    eng_content = models.TextField()
    kor_content = models.TextField()
    image_url = models.URLField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.eng_title = Crawler(self.target_url)[1]
        self.kor_title = Transla(*Crawler(self.target_url))
        self.eng_content = Crawler(self.target_url)[0]
        self.kor_content = Crawler(self.target_url)[0]
        self.image_url = Crawler(self.target_url)[3]

        return super().save(*args, **kwargs)

crawler/models.py
from django.db import models
from bs4 import BeautifulSoup
import requests
from googletrans import Translator

def Crawler(target_url):
    req = requests.get(target_url)
    html = req.text
    soup = BeautifulSoup(html, 'html.parser')
    body = soup.select(
        'body > div.fluid > article > div > div.l-main-container > div > div > div.l-main-container > div > div.article-entry.text > p'
        )
    contents_body = ''
    for ptag in body:
        contents_body += ptag.getText()

    title = soup.find("meta",  property="og:title")
    url = soup.find("meta",  property="og:url")
    image = soup.find("meta",  property="og:image")

    contents_title = title["content"] if title else "No Title"
    contents_url = url["content"] if url else "No Url"
    contents_image= image["content"] if image else ""

    return contents_body, contents_title, contents_url, contents_image

def Transla(contents_body, contents_title, contents_url, contents_image): 
    translator = Translator()
    translation = translator.translate(contents_title, src='en', dest='ko')
    return translation.text

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['target_url']

class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

accounts/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import redirect, render
from .models import Post
from .forms import PostForm, EditForm

def blog_list(request):
    qs = Post.objects.all()
    return render(request, 'blog/main.html', {
        'post_list': qs,
        })

def blog_detail(request, pk):
    post = Post.objects.get(pk=pk)
    qs = Post.objects.all()
    return render(request, 'blog/detail.html', {
        'post' : post,
        'post_list': qs,
        })

def blog_edit(request, pk):
    post = Post.objects.get(pk=pk)

    if request.method == 'POST':    
        form = EditForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect('blog:blog_detail', post.id)
    else:
    # if request.method == 'GET':
        form = EditForm(instance=post)

    return render(request, 'blog/crawler.html', {
        'form': form,
    })

def blog_delete(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:blog_list')
    return render(request, 'blog/delete.html', {
        'post': post,
    })

def profile(request):
    qs = Post.objects.all()
    return render(request, 'blog/profile.html', {
        'post_list': qs,
        })

def crawler_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return render(request, 'blog/crawler.html', {
                'form': form,
            })
    else:       
    # if request.method == 'GET':
        form = PostForm()

    return render(request, 'blog/crawler.html', {
        'form': form,
    })

crawler/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/crawler.html
{% extends "blog/layout.html" %}

{% block metatag %}
<meta name="og:title" content="" />
<meta name="og:image" content="" />
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table table-striped .table-hover">
                    {{ form.as_table }}
                </table>
                <input type="submit" class="btn btn-primary btn-block" />
            </form>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/delete.html
{% extends "blog/layout.html" %}

{% block metatag %}
<meta name="og:title" content="" />
<meta name="og:image" content="" />
{% endblock %}
{% block content %}

<h3>{{ post.title }}</h3>

<form action="" method="post">
    {% csrf_token %}
    <div style="height: 200px; background-color: pink; font-size: 30px; text-align: center; padding-top: 80px;">정말로 삭제하시겠습니까?</div>
    <input type="submit" value="삭제하겠습니다." class="btn btn-danger btn-block" />
</form>

{% endblock %}

blog/templates/blog/detail.html
{% extends "blog/layout.html" %}

{% block metatag %}
{% endblock %}

{% block content %}
<div class="container">
      <div class="blog-header">
        <p class="lead blog-description">해당 콘텐츠는 TechCrunch의 기사를 자동번역한 기사입니다.</p>
      </div>
      <div class="row">
        <div class="col-xs-12 blog-main">
          <div class="blog-post">
            <h2 class="blog-post-title">{{ post.kor_title }}</h2>
            <p class="blog-post-meta">{{ post.created_at }} by <a href="{{ post.target_url }}">TechCrunch</a></p>
            <div style="text-align: center; padding: 20px; padding-bottom: 40px;">
                <img src="{{ post.image_url }}">
            </div>
            <div class="col-xs-6">
                <h4>Auto-Translated</h4>
                <blockquote>
                <p>
                    {{ post.kor_content }}
                </p>
                </blockquote>
            </div>
            <div class="col-xs-6">
                <h4>Original Contents</h4>
                <blockquote>
                <p>
                    {{ post.eng_content }}
                </p>
                </blockquote>
            </div>
          </div>
        </div>
    </div>
    <div class="row">
<div class="container" style="height: 50px;">
    <div class="pull-right" style="height: 20px; display: block;">
        <a href={% url "blog:blog_list" %} class="btn btn-primary" role="button" style="width: 200px; display: inline; padding: 5px;">메인가기</a>
        <a href={% url "blog:blog_edit" post.id %} class="btn btn-info" role="button" style="width: 200px; display: inline; padding: 5px;">수정하기</a>
        <a href={% url "blog:blog_delete" post.id %} class="btn btn-danger" role="button" style="width: 200px; display: inline; padding: 5px;">삭제하기</a>
    </div>
</div>
<div class="container">
  {% for post in post_list reversed %}
    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <img src="{{ post.image_url }}" style="width: 202.5px; height: 120px;">
        <div class="caption">
          <h4 style="display: inline-block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; white-space: normal; line-height: 1.2; height: 2.4em; word-breka:keep-word;">{{ post.kor_title }}</h4>
          <p style="display: inline-block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; white-space: normal; line-height: 1.2; height: 6.0em; word-breka:keep-word;">{{ post.kor_content }}</p>
          <p><a href="{% url "blog:blog_detail" post.id %}" class="btn btn-primary" role="button">번역 보기</a> <a href="{{ post.target_url }}" class="btn btn-default" role="button">원문 보기</a></p>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

{% endblock %}

blog/templates/blog/layout.html
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
{% load staticfiles %}
<link rel="shortcut icon" href="{%  static 'favicon.ico' %}" type="image/x-icon" />
<link rel="icon" href="{%  static 'favicon.ico' %}" type="image/x-icon" />
<title>Transmedia</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Optional theme -->
<link rel="stylesheet" href="http://getbootstrap.com/examples/blog/blog.css">
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



{% block metatag %}
{% endblock %}

</head>
<body>
  <div style="text-align: center;">
    <a href={% url "blog:blog_list" %}><img src="https://preview.ibb.co/cegVBa/logo.png" alt="logo" border="0" style="height: 60px; padding: 10px;""></a>
  </div>
  <div class="blog-masthead ">
    <div class="container" style="text-align: center;">
      <nav class="blog-nav">
        <a class="blog-nav-item active" href="{% url 'blog:blog_list' %}">Main</a>
        <a class="blog-nav-item" href="{% url 'blog:crawler_new' %}">Crawler</a>
        <a class="blog-nav-item" href="{% url 'blog:profile' %}">About</a>
      </nav>
    </div>
  </div>

{% block content %}
{% endblock %}

</body>
  <footer class="blog-footer">
    <p>Auto Translation Media Developed By Kevin Baek</p>
    <p>
      <a href="#">Back to top</a>
    </p>
  </footer>

  </body>
</html>

blog/templates/blog/main.html
{% extends "blog/layout.html" %}

{% block metatag %}
{% endblock %}

{% block content %}
<div style="background-color: #333;">
<div class="container">
  <div style="height: 20px;"></div>
  {% for post in post_list|slice:":1" reversed %}
  <div class="row featurette">
      <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading" style="display: inline-block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; white-space: normal; line-height: 1.2; height: 2.4em; color: white; word-breka:keep-word;">{{ post.kor_title }}</h2>
          <p class="lead" style="display: inline-block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; white-space: normal; line-height: 1.2; height: 4.8em; color: #aaa; word-breka:keep-word;">{{ post.kor_content }}</p>
          <p><a href="{{ post.target_url }}" class="btn btn-default pull-right" role="button">원문 보기</a><a href="{% url "blog:blog_detail" post.id %}" class="btn btn-primary pull-right" role="button">번역 보기</a></p>
      </div>
      <div class="col-md-5 col-md-pull-7" style="paddig: 15px;">
          <img class="featurette-image img-responsive center-block img-thumbnail" src="{{ post.image_url }}" alt="Main Article">
      </div>
  </div>
  <div style="height: 20px;"></div>
</div>
</div>
  {% endfor %}
<div class="container">
  <div class="row">
  <div style="height: 20px;"></div>
  {% for post in post_list|slice:"1:" reversed %}
    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <img src="{{ post.image_url }}" style="width: 202.5px; height: 120px;">
        <div class="caption">
          <h4 style="display: inline-block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; white-space: normal; line-height: 1.2; height: 2.4em; word-breka:keep-word;">{{ post.kor_title }}</h4>
          <p style="display: inline-block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; white-space: normal; line-height: 1.2; height: 6.0em; word-breka:keep-word;">{{ post.kor_content }}</p>
          <p><a href="{% url "blog:blog_detail" post.id %}" class="btn btn-primary" role="button">번역 보기</a> <a href="{{ post.target_url }}" class="btn btn-default" role="button">원문 보기</a></p>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
</div>

{% endblock %}

blog/templates/blog/profile.html
{% extends "blog/layout.html" %}

{% block metatag %}
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
      <div class="col-xs-6 col-md-3">
        My Profile
      </div>
  </div>
</div>

{% endblock %}